name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          parallel: true
          record: false
          build: npm run build
          command: npm run test:e2e
      - name: Unit tests run
        run: npm run test:unit
      - name: Translation validation
        run: npm run translation-key-check
